# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
    - id: backup-restore-operator
      main: ./main.go
      goos:
        - linux
      goarch:
        - amd64
        - arm64
      binary: backup-restore-operator
      ldflags:
        - -extldflags
        - -static
        - -s
        - -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
archives:
    - id: backup-restore-operator
      builds:
        - backup-restore-operator 
      name_template: '{{ .Binary }}-{{ .Arch }}'
release:
  prerelease: auto
  extra_files:
    - glob : ./build/artifacts/*.tgz
  # This might be a bit expensive (rate-limiting speaking), so it is only done
  # when the upload of an artifact fails with a 422 (which means it already
  # exists in the release).
  # We then grab the list of artifacts from the release, and delete the file
  # that matches the one we're trying to upload.
  # GoReleaser will then retry its upload.
  replace_existing_artifacts: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
