name : Publish Images

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: docker.io
  REPO : rancher


jobs:
  ci :
    uses: rancher/backup-restore/.github/workflows/ci.yaml@release/v5.0
    permissions:
      contents: read
  push:
    permissions:
      contents : read
      id-token: write
    name : Build and push BRO images
    runs-on : ubuntu-latest
    steps:
      - name : Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # setup tag name
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo $GITHUB_REF | sed -e "s|refs/tags/||") >> $GITHUB_ENV
      - name: Build and push BRO image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./package/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/backup-restore-operator:${{ env.TAG_NAME }}
          platforms: linux/amd64,linux/arm64